/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({props, scale}) {
  const { nodes, materials } = useGLTF('/ChessQueenModel/scene.gltf')
  return (
    <group scale={scale ? scale : window.screen.width < 600 ? 0.06 : 0.13} {...props} dispose={null}>
      <mesh geometry={nodes.geo1_Material_1_0.geometry} material={materials.Material_1} />
    </group>
  )
}

useGLTF.preload('/ChessQueenModel/scene.gltf')
